[package]
name = "actix-limitation"
version = "0.1.4"
authors = ["errmac-v"]
description = "A rate limiter using a fixed window counter for arbitrary keys, backed by Redis for actix-web."
keywords = ["actix-web", "rate-api", "rate-limit", "limitation"]
categories = ["asynchronous", "web-programming"]
repository = "https://github.com/actix/actix-extras.git"
license = "MIT"
edition = "2018"

[dependencies]
actix-session = "0.4"
actix-web = "3"
chrono = "0.4"
futures = "0.3.7"
log = "0.4"
redis = "0.16"
time = "0.2.23"

[dev-dependencies]
actix-rt = "1.1.1"
uuid = { version = "0.8.1", features = ["v4"] }
